version: '3'

services:
    mysql:
        image: mysql:8.0.28
        restart: on-failure
        ports:
            - "10306:3306"
        command: >
            --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: shopify
            MYSQL_ROOT_HOST: '%'

    php-cli:
        tty: true
        build:
            context: ./php/cli
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        ports:
            - "3456:3456"
        command: php -r "while (true) { sleep(86400); }"
        restart: always
        working_dir: /var/www/html/shopify-app-php
        volumes:
            - ./../../shopify-app-php:/var/www/html/shopify-app-php:rw
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
